config/routes.rb
Rails.application.routes.draw do

  get '/authors', to: 'authors#index', as: 'authors'

  get '/authors/new', to: 'authors#new', as: 'new_author'
  post '/authors', to: 'authors#create'

  get '/authors/:id', to: 'authors#show', as: 'author'

  get '/authors/:id/edit', to: 'authors#edit', as: 'edit_author'
  patch '/authors/:id', to: 'authors#update'
  put '/authors/:id', to: 'authors#update'

  delete '/authors/:id', to: 'authors#destroy'

end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  year       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Author < ActiveRecord::Base

  has_one :profile, # Name of methods (rolename in class diagram)
          class_name: "AuthorProfile", # Name of "had" class
          foreign_key: "author_id" # Name of foreign key column

  has_many :books

	validates :first_name, presence: true, length: { maximum: 50 }

end

app/models/author_profile.rb
# == Schema Information
#
# Table name: author_profiles
#
#  id         :integer          not null, primary key
#  birthplace :string
#  bio        :text
#  awards     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  author_id  :integer
#

class AuthorProfile < ActiveRecord::Base

  belongs_to :author, # Name of the methods (rolename in class diagram)
             class_name: "Author", # Name of other class
             foreign_key: "author_id" # Name of foreign key column 

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string
#  year       :integer
#  summary    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  author_id  :integer
#

class Book < ActiveRecord::Base

  belongs_to :author

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
  	# Grab all authors.
  	@authors = Author.all
  end

  def new
  	@author = Author.new
  end

  def create
  	@author = Author.new(params.require(:author).permit(:first_name, :last_name, :year))
  	if @author.save
      flash[:notice] = "User created!"
  		redirect_to author_url(@author)
  	else
      flash.now[:alert] = "Error(s) in form!"
      @author.errors.full_messages.each do |message|
        flash.now[:alert] += " "
        flash.now[:alert] += message
      end
  		render 'new'
  	end
  end

  def show
    @author = Author.find(params[:id])
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(params.require(:author).permit(:first_name, :last_name, :year))
      flash[:notice] = "User updated!"
      redirect_to author_url(@author)
    else
      flash.now[:alert] = "Errors in form!"
      render 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= form_for(@author) do |f| %>

<p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
</p>
<p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
</p>
<p>
    <%= f.label :year %><br>
    <%= f.text_field :year %>
</p>
<p>
	<%= f.submit %>
</p>

<% end %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<table>
	<tr>
		<td>First Name</td>
		<td>Last Name</td>
		<td>Year</td>
		<td>Links</td>
	</tr>
<% @authors.each do |author|%>
	<tr>
		<td><%= author.first_name %></td>
		<td><%= author.last_name %></td>
		<td><%= author.year %></td>
		<td>[<%= link_to "Show", author_path(author) %>,
			 <%= link_to "Edit", edit_author_path(author) %>,
			 <%= link_to "Delete", author_path(author), method: :delete %>]
		</td>
	</tr>
<% end %>
</table>

<p>
	<%= link_to "Create New Author", new_author_path %>
</p>

app/views/authors/new.html.erb
<h1>Create New Author</h1>

<%= form_for(@author) do |f| %>

<p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
</p>
<p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
</p>
<p>
    <%= f.label :year %><br>
    <%= f.text_field :year %>
</p>
<p>
	<%= f.submit %>
</p>

<% end %>

app/views/authors/show.html.erb
<h1>Author</h1>

<ul>
	<li>First Name: <%= @author.first_name %></li>
	<li>Last Name: <%= @author.last_name %></li>
	<li>Year: <%= @author.year %></li>
  <% if @author.profile %>
    <li>Birthplace: <%= @author.profile.birthplace %></li>
  <% end %>
  <% if @author.books.size > 0 %>
    <li>Books:
      <ul>
        <% @author.books.each do |book| %>
        <li><%= book.title %> (<%= book.year %>)</li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

<p>
	<%= link_to "Show All Authors", authors_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookatalog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
  <hr>
  <p><%= flash[:notice] %></p>
  <hr>
<% end %>
<% if flash[:alert] %>
  <hr>
  <p>Error: <%= flash[:alert] %></p>
  <hr>
<% end %>

<%= yield %>

</body>
</html>